name: "Changelog action"
description: "Updates a changelog file for projects in the oscar-system universe"

inputs:
  tier1:
    description: 'Tier 1 in multi tier changelog'
    required: true
  tier2:
    description: 'Tier 2 in multi tier changelog'
    required: true
  version:
    description: "New version number"
    required: false

outputs:
  chagenlogfile:
    description: "The updated changelog file"
    value: ""

runs:
  using: 'composite'
  steps:
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: "make changelog"
      id: make-changelog
      shell: bash
      run: "python3 release-notes.py ${{ inputs.version }}"
